### ISSUE TITLE
Incorrect webpack file

### ISSUE THREAD

**Issue by obstschale** [htmlburger/carbon-field-template#4]
I have an issue with your webpack config. In `webpack.config.js` you reference files, which are not available.

https://github.com/htmlburger/carbon-field-template/blob/master/webpack.config.js#L51-L61

**Comment by atanas-dev** [comment]
Hi @obstschale ,

The template requires that you have `htmlburger/carbon-fields` installed alongside as the build process relies on packages from it. Depending on where you install it you have to adjust your webpack file as explained in this comment:
```
/**
 * This path assumes that Carbon Fields and the current template
 * are both in the `/vendor` directory inside your theme - change the path if needed.
 */
const root = path.resolve(__dirname, '../../htmlburger/carbon-fields');
```

Simply adjust the `root` value to point to carbon fields' directory and the build process will work.

**Comment by obstschale** [comment]
I have carbon fields installed. But there is not `htmlburger/carbon-fields/assets/dist` directory.

**Comment by obstschale** [comment]
Additionally, I just figured out that I had to run `npm install` within `htmlburger/carbon-fields` otherwise there is an error. You should add this to your README file :)

**Comment by obstschale** [comment]
Oh I just saw I also had to run `npm run css` and `npm run js` in `htmlburger/carbon-fields`. Now the webpack config runs without errors.

I know documenting stuff is not the most fun job, but I would like to see a better tutorial how to build extending fields. The readme is really helpful :/

**Comment by atanas-dev** [comment]
Did you install Carbon Fields through composer? If you cloned/downloaded it from Github then dist files will be missing since we ignore them in git branches (only the `release` branch has them).
With the dist files you do not need to run any command in the carbon-fields directory.

You should keep Carbon Fields installed through composer as that is the official installation channel.

**Comment by obstschale** [comment]
I have installed carbon fields via composer.

**Comment by obstschale** [comment]
It seems composer fetched `dev-master`. I just required carbon-fields again with a specific version and the `dist/` dir is there

**Comment by atanas-dev** [comment]
Since we follow SemVer I would suggest you use a version pattern such as `^2.0`.

Let me know if any issue mentioned is outstanding now that you have the dist files.

**Comment by obstschale** [comment]
:+1: Thanks for the help. I just got it working. The difficulties were, that I try to add an extended field into my plugin. So I merged this repo into my plugin, which was not that obvious (for me, who did not yet fully understand webpack ^^)

**Comment by atanas-dev** [comment]
No worries : )
